// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./internal/check/cmd.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of checker interface
type Mockchecker struct {
	ctrl     *gomock.Controller
	recorder *_MockcheckerRecorder
}

// Recorder for Mockchecker (not exported)
type _MockcheckerRecorder struct {
	mock *Mockchecker
}

func NewMockchecker(ctrl *gomock.Controller) *Mockchecker {
	mock := &Mockchecker{ctrl: ctrl}
	mock.recorder = &_MockcheckerRecorder{mock}
	return mock
}

func (_m *Mockchecker) EXPECT() *_MockcheckerRecorder {
	return _m.recorder
}

func (_m *Mockchecker) Check() error {
	ret := _m.ctrl.Call(_m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockcheckerRecorder) Check() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Check")
}

func (_m *Mockchecker) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockcheckerRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}
