language: "go"
sudo: false
go:
  - 1.16.x
  - 1.12.x
  - 1.11.x
services:
  - docker
env:
  global:
    - TMPDIR=/tmp
install:
  - make dep
script:
  - make lint
  - make test
  - make integration
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -f .coverage/combined.cover.out
