#!/usr/bin/env bash

# Generate a combined coverage
if test -f "go.mod"; then
    export GOFLAGS="-mod=vendor -buildvcs=false ${GOFLAGS:+}"
    export GOPROXY=https://proxy.golang.org
    export GO111MODULE=on
fi

mkdir -p .coverage
gocovmerge .coverage/*.cover.out > .coverage/combined.cover.out
gocov convert .coverage/combined.cover.out | gocov-xml > .coverage/combined.xml
go tool cover -func .coverage/combined.cover.out
