#!/usr/bin/env bash

# Add a Micros service descriptor to the current project.

RENDERDIR="$(mktemp)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" git@bitbucket.org:asecurityteam/template-micros.git "$@"
mv "${RENDERDIR}/**/*" .
rm -rf "${RENDERDIR}"
