#!/usr/bin/env bash

# Runs yamllint against all yaml files in current directory
# Will read from a .yamllint config file if one is present in current directory
# More about yamllint: https://github.com/adrienverge/yamllint

yamllint .
