#!/usr/bin/env bash

# Add the standard go docker file to the current project.

shopt -s dotglob
RENDERDIR="$(mktemp -d)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" gh:asecurityteam/template-go-docker "$@"
mv "${RENDERDIR}"/**/* .
rm -rf "${RENDERDIR}"
