#!/usr/bin/env bash

# This is the entry point for the repo management CLI.

# Capture the target command and pop it from the args
COMMAND="$1"
shift

case ${COMMAND} in
    all)
        sdcli_repo_all "$@"
        ;;
    go)
        sdcli_repo_go "$@"
        ;;
    *)
        echo "Unknown repo command ${COMMAND}"
        sdcli_help
        exit 1
        ;;
esac
