#!/usr/bin/env bash

# Run the static analysis suite for go projects.

if test -f "go.mod"; then
    export GOFLAGS='-mod=vendor'
    export GOPROXY="https://proxy.golang.org,direct"
    export GO111MODULE=on
fi

golangci-lint run --config .golangci.yaml ./... -v
