#!/usr/bin/env bash

# Run go unit tests and generate a coverage report. Our coverage reports
# actively ignore main.go for services by removing the top level package from
# the set of covered packages. Library support is enabled by checking the root
# for a main.go and skipping the removal of the top package if one is not found.

mkdir -p .coverage
PKGS="$(go list ./... | paste -sd "," -)"
if [[ -f "${PWD}/main.go" ]]; then
    PKGS="$(go list ./... | sed 1d | paste -sd "," -)"
fi

if test -f "go.mod"; then
    GO111MODULE=on go test -mod=vendor -v -cover -coverpkg="${PKGS}" -coverprofile=.coverage/unit.cover.out ./...
else
    go test -v -cover -coverpkg="${PKGS}" -coverprofile=.coverage/unit.cover.out ./...
fi

_EXIT_CODE=$?
gocov convert .coverage/unit.cover.out | gocov-xml > .coverage/unit.xml
exit ${_EXIT_CODE}
