#!/usr/bin/env bash

# Add the standard go project skeleton.

shopt -s dotglob
RENDERDIR="$(mktemp -d)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" gh:asecurityteam/template-go-layout "$@"
mv "${RENDERDIR}"/**/* .
rm -rf "${RENDERDIR}"
