#!/usr/bin/env bash

# Audit the repo to verify that it implements the repo contract.

if [[ ! -f "${PWD}/Makefile" ]]; then
    echo "Missing Makefile"
    exit 1
fi

for _rule in "dep lint test integration coverage build doc run deploy"; do
    if [[ "$(grep "${_rule}:" "${PWD}/Makefile")" == "" ]]; then
    echo "Missing dep rule in Makefile."
    exit 1
fi
done
