#!/usr/bin/env bash

# Run the static analysis suite for go projects.

if test -f "go.mod"; then
    GO111MODULE=on golangci-lint run --config .golangci.yaml ./... -v
else
    golangci-lint run --config .golangci.yaml ./... -v
fi
