#!/usr/bin/env bash

# Add a travis yaml file to the current project.

shopt -s dotglob
RENDERDIR="$(mktemp -d)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" gh:asecurityteam/template-go-travis "$@"
mv "${RENDERDIR}"/**/* .
rm -rf "${RENDERDIR}"


