#!/usr/bin/env bash

# Install go project dependencies.
# NOTE: This will begin to transition to go mod once the go1.12 release
# is finalized.

if test -f "go.mod"; then
    export GOFLAGS='-mod=vendor'
    export GOPROXY=https://proxy.golang.org
    export GO111MODULE=on
    go mod vendor
else
    echo "go.mod not found, giving up" 1>&2
    exit 1
fi
