#!/usr/bin/env bash

# Add license and contributing information to the current project.

shopt -s dotglob
RENDERDIR="$(mktemp -d)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" gh:asecurityteam/template-oss "$@"
mv "${RENDERDIR}"/**/* .
rm -rf "${RENDERDIR}"

