#!/usr/bin/env bash

# This is the top-level entry point for the CLI. It routes to subcommands
# for major features.

# Configure the locale to avoid ASCII/UTF8 conflicts.
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Capture the package being accessed.
PACKAGE=$1
# Pop the $1 arg off the $@ array.
shift

case ${PACKAGE} in
    go)
        sdcli_go "$@"
        ;;
    repo)
        sdcli_repo "$@"
        ;;
    *)
        echo "Unknown command ${PACKAGE}"
        exit 1
        ;;
esac
