#!/usr/bin/env bash

#Lists the versions of the various languages and applications installed on SDCLI's image
# suppress color coding if TERM was not set
: "${TERM:=dumb}"
export TERM

YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)
NORMAL=$(tput sgr0)


printf "%s\nGo-related versions\n%s" "${GREEN}" "${NORMAL}"

go version
golangci-lint --version
dep version

printf "%s\nPython-related versions\n%s" "${CYAN}" "${NORMAL}"

python --version
pylint --version
pytest --version
pipenv --version
coverage --version

printf "%s\nEtc\n%s" "${YELLOW}" "${NORMAL}"

cookiecutter --version

yamllint --version

