#!/usr/bin/env bash

# Capture the target command and pop it from the args
COMMAND="$1"
shift

case ${COMMAND} in
    create)
        sdcli_repo_go_create "$@"
        ;;
    add-layout)
        sdcli_repo_go_add-layout "$@"
        ;;
    add-lint)
        sdcli_repo_go_add-lint "$@"
        ;;
    add-docker)
        sdcli_repo_go_add-docker "$@"
        ;;
    *)
        echo "Unknown all repo command ${COMMAND}"
        exit 1
        ;;
esac
