#!/usr/bin/env bash

# Add a travis yaml file to the current project.

RENDERDIR="$(mktemp)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" gh:asecurityteam/template-go-travis "$@"
mv "${RENDERDIR}/**/*" .
rm -rf "${RENDERDIR}"


