#!/usr/bin/env bash

# This is the top-level entry point for the CLI. It dispatches
# commands by joining all args with an _. It also allows extra
# arguments to pass through by putting them after a -- argument.

# Configure the locale to avoid ASCII/UTF8 conflicts.
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

declare -a COMMAND_PATH
declare -a EXTRA_ARGS
IN_EXTRA=false

for CURRENT_ARG in "$@"; do
    if [[ ${CURRENT_ARG} == "--" ]]; then
        IN_EXTRA=true
        continue
    fi
    if [[ ${IN_EXTRA} == true ]]; then
        EXTRA_ARGS+=("${CURRENT_ARG}")
    else
        COMMAND_PATH+=("${CURRENT_ARG}")
    fi
done

join_by() {
    local IFS="$1"; shift; echo "$*";
}

sdcli_"$(join_by "_" "${COMMAND_PATH[@]}")" "${EXTRA_ARGS[@]}"
