#!/usr/bin/env bash

# Run go integration tests and generate a coverage artifact.
# Our go projects are expected to place integration tests in a
# /tests directory accessible from the repository root and all
# test files must have a '+build integration' tag in them.
#
# If no integration tests are found then the command reports
# that there are no tests and exists successfully.

mkdir -p .coverage

INTTESTS=$(go test -tags=integration -list . ./tests)
FAIL="$(echo "${INTTESTS}" | grep 'FAIL')"
if [[ ${FAIL} != "" ]]; then
    echo "A setup or compilation failure occurred."
    exit 1
fi
FOUND="$(echo "${INTTESTS}" | grep 'ok')"
if [[ ${FOUND} == "" ]]; then
    echo "No integration tests found."
    exit 0
fi

PKGS="$(go list ./... | paste -sd "," -)"
if [[ -f "${PWD}/main.go" ]]; then
    PKGS="$(go list ./... | sed 1d | paste -sd "," -)"
fi

if test -f "go.mod"; then
    GO111MODULE=on go test -mod=vendor -v -tags=integration -cover -coverpkg="${PKGS}" -coverprofile=.coverage/integration.cover.out ./tests
else
    go test -v -tags=integration -cover -coverpkg="${PKGS}" -coverprofile=.coverage/integration.cover.out ./tests
fi

_EXIT_CODE=$?
gocov convert .coverage/integration.cover.out | gocov-xml > .coverage/integration.xml
exit ${_EXIT_CODE}
