#!/usr/bin/env bash

## Add a DAC package to the current project.

RENDERDIR="$(mktemp)"
mkdir -p "${RENDERDIR}"
cookiecutter -f -o "${RENDERDIR}" git@bitbucket.org:asecurityteam/template-dac.git "$@"
mv "${RENDERDIR}/**/*" .
rm -rf "${RENDERDIR}"
