#!/usr/bin/env bash

# Audit the repo to verify that it implements the repo contract.
if [[ ! -f "${PWD}/Makefile" ]]; then
    echo "Missing Makefile"
    exit 1
fi

declare -a rules=(dep lint test integration coverage build doc run deploy)
for _rule in "${rules[@]}"; do
    if [[ "$(grep "${_rule}:" "${PWD}/Makefile")" == "" ]]; then
    echo "Missing ${_rule} rule in Makefile."
    exit 1
fi
done
